### ISSUE TITLE
ImoHash.SumFile returns "Seek: invalid offset" error if called on a file with a size that is greater than sampleThreshold but less than sampleSize

### ISSUE THREAD

**Issue by Hakkin** [kalafut/imohash#15]
See https://github.com/schollz/croc/issues/786#issuecomment-2299693667

The offending code is here:
https://github.com/kalafut/imohash/blob/3f885db6c6c295ad8076096f9f02238490b91584/imohash.go#L107-L131

imohash tries to seek `-imo.sampleSize` from the end of the reader, but does not verify `imo.sampleSize <= f.Size()` before doing so, leading to Seek returning an error.

Here's a playground link demonstrating this with `Sum` (panics rather than returning an error): https://go.dev/play/p/wKCwBAo6nsZ

Note that this situation (seemingly?) isn't possible with the default SampleSize and SampleThreshold, since the default SampleThreshold>SampleSize. It's only an issue if you set custom values and SampleSize>SampleThreshold. I don't know the intricacies of the algorithm, so I'm not sure if it's even correct or makes sense to set the values like this.

**Comment by kalafut** [comment]
This is a good catch and not a particularly obscure edge case. Let me think about the correct way to handle it. Note: I'm traveling, and a PR might take a few days.

**Comment by kalafut** [comment]
The most reasonable change is probably to hash the whole file if the length is less than the sample threshold (already handled) OR is less than the sample size.
